"""empty message

Revision ID: 1883115ca1e9
Revises: 5a150bfe1f76
Create Date: 2025-06-27 11:52:36.262363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1883115ca1e9'
down_revision = '5a150bfe1f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
